### PR TITLE
changes

### PR DESCRIPTION
**Pull request by RyanKung**
1. support for python 3.5 and above;
2. check `is_ip` first then get ip via hostname; 
3. support `doctest` on IP.find function

### CODE REVIEW

**Comment by lxyu** [comment]
It seems the `socket.gethostbyname` can handle both the IP verification and resolve domain name, so I don't see why we need `is_ip`?

``` py
>>> socket.gethostbyname("ele.me")
'58.216.25.33'
>>> socket.gethostbyname("119.29.29.29")
'119.29.29.29'
>>> socket.gethostbyname("abc")
gaierror: [Errno -2] Name or service not known
```

**Comment by RyanKung** [comment]
Yeah, I knew that the `socket.gethostbyname` is actually works for both IP and 'hostname',  and works same as what 'is_ip' does, ["If name is an IPv4 address, no lookup is performed"](http://man7.org/linux/man-pages/man3/gethostbyname.3.html). 

But I thought that, without knowledge of the the detail implementation of `socket.gethostbyname`, it is hard to find out what is actually happening here, and a checkout function may make the code more clearly for understanding.

**Comment by wantongtang** [comment]
once task added in crontab ,there is a problem that code can't run

**Comment by lxyu** [comment]
@wantongtang can you explain the problem?

**Pull request closed without merging**
